name: Merge to Master

permissions:
  packages: write

on:
  push:
    branches:
      - master

jobs:
    push-nuget:
        name: Push to Nuget (preview)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: python -m pip install -r ./scripts/requirements.txt
            - run: python ./scripts/deploy-nuget.py --prerelease --username DeployBot --token ${{ secrets.GITHUB_TOKEN }}